In [ ]:
import pandas as pd

a=[]
for i in range(1,21):
    a.append(i)

a

In [ ]:
[x for x in range(1,21)]

In [ ]:
[x for x in range(1,21,2)]

In [ ]:
sum([x for x in range(1,21,2)])

In [ ]:
(lambda a,b: pow(a,b))

In [ ]:
import numpy as np
from numpy.random import rand
import matplotlib.pyplot as plt
x = np.random.uniform(-2,3,100)
y = np.zeros(100)
plt.scatter(x,y)
plt.show

In [ ]:
x = np.random.uniform(-2,3,100)
x


In [ ]:
import this


In [ ]:
y=np.zeros(100)
y

In [ ]:
a=[[11,12,13],[21,22,23]]
A = np.array(a)
A

In [ ]:
A.T

In [ ]:
np.zeros((30,5))

In [ ]:
np.identity(4)

In [ ]:
score_list=[95,100,80,90,95]
data = pd.Series(score_list)
data

In [ ]:
data.values()

In [ ]:
data

In [ ]:
data[1:3]

In [ ]:
data = pd.Series(score_list, index=['Korean', 'math', 'science', 'English', 'algebra'])
data['science']

In [ ]:
A=np.array([[1,1,0],[0,1,1],[1,1,1]])
Ainv=np.linalg.inv(A)
Ainv

In [87]:
import numpy as np
height = np.array([183,150,180,197,160,175])
height = height.T # 여기에 코드 삽입. 2차원인 형태로 값을 변환. 열벡터로 변환
math=np.array([85,45,80,99,45,75])
height=height.reshape(6,1)
height.shape

height = height.reshape(6,1)
height.shape

(6, 1)

In [89]:
d1 = np.zeros(2)
d2 = np.zeros((2,3))

print("d1=", d1, "\nd2=", d2)


d1= [0. 0.] 
d2= [[0. 0. 0.]
 [0. 0. 0.]]


In [80]:
import numpy as np
height = np.array([183,150,180,197,160,175])
height

array([183, 150, 180, 197, 160, 175])

In [83]:
height.reshape(1,6)

array([[183, 150, 180, 197, 160, 175]])