In [ ]:
import pandas as pd

a=[]
for i in range(1,21):
    a.append(i)

a

In [ ]:
[x for x in range(1,21)]

In [ ]:
[x for x in range(1,21,2)]

In [ ]:
sum([x for x in range(1,21,2)])

In [ ]:
(lambda a,b: pow(a,b))

In [ ]:
import numpy as np
from numpy.random import rand
import matplotlib.pyplot as plt
x = np.random.uniform(-2,3,100)
y = np.zeros(100)
plt.scatter(x,y)
plt.show

In [3]:
import numpy as np
from numpy.random import rand
import matplotlib.pyplot as plt
x = np.linspace(-2,3,100)
x

array([-2.        , -1.94949495, -1.8989899 , -1.84848485, -1.7979798 ,
       -1.74747475, -1.6969697 , -1.64646465, -1.5959596 , -1.54545455,
       -1.49494949, -1.44444444, -1.39393939, -1.34343434, -1.29292929,
       -1.24242424, -1.19191919, -1.14141414, -1.09090909, -1.04040404,
       -0.98989899, -0.93939394, -0.88888889, -0.83838384, -0.78787879,
       -0.73737374, -0.68686869, -0.63636364, -0.58585859, -0.53535354,
       -0.48484848, -0.43434343, -0.38383838, -0.33333333, -0.28282828,
       -0.23232323, -0.18181818, -0.13131313, -0.08080808, -0.03030303,
        0.02020202,  0.07070707,  0.12121212,  0.17171717,  0.22222222,
        0.27272727,  0.32323232,  0.37373737,  0.42424242,  0.47474747,
        0.52525253,  0.57575758,  0.62626263,  0.67676768,  0.72727273,
        0.77777778,  0.82828283,  0.87878788,  0.92929293,  0.97979798,
        1.03030303,  1.08080808,  1.13131313,  1.18181818,  1.23232323,
        1.28282828,  1.33333333,  1.38383838,  1.43434343,  1.48

In [ ]:
x = np.random.uniform(-2,3,100)
x


In [ ]:
import this


In [ ]:
y=np.zeros(100)
y

In [ ]:
a=[[11,12,13],[21,22,23]]
A = np.array(a)
A

In [ ]:
A.T

In [ ]:
np.zeros((30,5))

In [ ]:
np.identity(4)

In [ ]:
score_list=[95,100,80,90,95]
data = pd.Series(score_list)
data

In [ ]:
data.values()

In [ ]:
data

In [ ]:
data[1:3]

In [ ]:
data = pd.Series(score_list, index=['Korean', 'math', 'science', 'English', 'algebra'])
data['science']

In [ ]:
A=np.array([[1,1,0],[0,1,1],[1,1,1]])
Ainv=np.linalg.inv(A)
Ainv

In [87]:
import numpy as np
height = np.array([183,150,180,197,160,175])
height = height.T # 여기에 코드 삽입. 2차원인 형태로 값을 변환. 열벡터로 변환
math=np.array([85,45,80,99,45,75])
height=height.reshape(6,1)
height.shape

height = height.reshape(6,1)
height.shape

(6, 1)

In [89]:
d1 = np.zeros(2)
d2 = np.zeros((2,3))

print("d1=", d1, "\nd2=", d2)


d1= [0. 0.] 
d2= [[0. 0. 0.]
 [0. 0. 0.]]


In [1]:
import numpy as np
height = np.array([183,150,180,197,160,175])
height

array([183, 150, 180, 197, 160, 175])

In [2]:
height.reshape(1,6)

array([[183],
       [150],
       [180],
       [197],
       [160],
       [175]])