# numpy를 이용한 선형대수

* 원문: [데이터사이언스 스쿨](https://datascienceschool.net/02%20mathematics/02.01%20%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%99%80%20%ED%96%89%EB%A0%AC.html)

선형대수(linear algebra)는 데이터 분석에 필요한 각종 계산을 돕는 학문이다. 데이터 분석을 하려면 수많은 숫자로 이루어진 데이터를 다루어야 한다. 하나의 데이터가 수십 개에서 수만 개의 숫자로 이루어져 있을 수도 있고, 또 이러한 데이터 수만 개가 하나의 집합을 이루고 있을 수도 있다.

선형대수를 사용하면 대량의 데이터를 포함하는 복잡한 계산 과정을 몇 글자 되지 않는 간단한 수식으로 서술할 수 있다. 따라서 데이터를 다루는 과정을 정확하고 간단하게 서술할 수 있다. 이를 위해 우선 선형대수에서 사용되는 여러 기호와 개념을 익혀보자.

## 데이터의 유형

선형대수에서 다루는 데이터는 개수나 형태에 따라 크게 **스칼라(scalar), 벡터(vector), 행렬(matrix), 텐서(tensor)** 유형으로 나뉜다. 스칼라는 숫자 하나로 이루어진 데이터이고, 벡터는 여러 숫자로 이루어진 데이터 레코드(data record)이며, 행렬은 이러한 벡터, 즉 데이터 레코드가 여럿인 데이터 집합이라고 볼 수 있다. 텐서는 같은 크기의 행렬이 여러 개 있는 것이라고 생각하면 된다.

In [3]:
import numpy as np

In [18]:
# 열 벡터
x1 = np.array([[5.1], [3.5], [1.4], [0.2]])
print(x1)
print(x1.shape)


[[5.1]
 [3.5]
 [1.4]
 [0.2]]
(4, 1)


In [19]:
# 행 벡터
x2 = np.array([5.1, 3.5, 1.4, 0.2])
print(x2)

print(x2.shape, " <= 행벡터의 shape는 이런식으로 그냥 숫자로 나온다...?")


[5.1 3.5 1.4 0.2]
(4,)  <= 행벡터의 shape는 이런식으로 그냥 숫자로 나온다...?


In [6]:
# 행렬
A = np.array([[11,12,13],[21,22,23]])
print(A)
print(A.shape)

[[11 12 13]
 [21 22 23]]
(2, 3)


In [7]:
# 전치행렬
print(A.T)

[[11 21]
 [12 22]
 [13 23]]


In [24]:
# 벡터의 전치는?
print("x1= \n", x1) #열벡터
print(x1.shape)
print("x1의 전치 = ", x1.T)  #행벡터
print(x1.T.shape)

print("x2= \n", x2) #행벡터
print(x2.shape)
print("x2의 전치 = ", x2.T) # 열백터
print(x2.T.shape)

x1= 
 [[5.1]
 [3.5]
 [1.4]
 [0.2]]
(4, 1)
x1의 전치 =  [[5.1 3.5 1.4 0.2]]
(1, 4)
x2= 
 [5.1 3.5 1.4 0.2]
(4,)
x2의 전치 =  [5.1 3.5 1.4 0.2]
(4,)


In [26]:
# 빈 행렬 만들기
print(np.zeros((3, 1))) #하나의 숫자를 튜플(튜플은 괄호안에 들어가 있는 형태임)의 형태로 넣어주는것임

[[0.]
 [0.]
 [0.]]


In [27]:
# 일 벡터 만들기
np.ones((3, 1)) #크기


array([[1.],
       [1.],
       [1.]])

In [30]:
# 대각행렬 만들기(diag 이용)
print(np.diag([1, 2, 3]))
print(np.diag([2,2,2]))


[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[2 0 0]
 [0 2 0]
 [0 0 2]]


In [31]:
# 항등행렬 만들기
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 행렬의 연산

In [33]:
a=[10,11,12,13,14]
b=[0,1,2,3,4]

x = np.array([10, 11, 12, 13, 14])
y = np.array([0, 1, 2, 3, 4])

In [34]:
x + y

array([10, 12, 14, 16, 18])

In [35]:
print(a+b) #리스트가 그저 합쳐짐..

#리스트의 값들을 더해주려면 밑에 과정들을 거쳐야됨
result=[]
for i,h in zip(a,b):
  result.append(i+h)
print(result)


[10, 11, 12, 13, 14, 0, 1, 2, 3, 4]
[10, 12, 14, 16, 18]


In [36]:
x - y


array([10, 10, 10, 10, 10])

\begin{split}
\begin{align}
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
+
\begin{bmatrix}
10 & 20 \\
30 & 40 \\
\end{bmatrix}
-
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
=
\begin{bmatrix}
14 & 24 \\
34 & 44
\end{bmatrix}
\end{align}
\end{split}

In [37]:
np.array([[5, 6], [7, 8]]) + np.array([[10, 20], [30, 40]]) - np.array([[1, 2], [3, 4]])

array([[14, 24],
       [34, 44]])

\begin{split}
\begin{align}
c
\begin{bmatrix}
x_1 \\
x_2
\end{bmatrix}
=
\begin{bmatrix}
cx_1 \\
cx_2
\end{bmatrix}
\end{align}
\end{split}
\begin{split}
\begin{align}
c
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
=
\begin{bmatrix}
ca_{11} & ca_{12} \\
ca_{21} & ca_{22}
\end{bmatrix}
\end{align}
\end{split}

\begin{split}
\begin{align}
\begin{bmatrix}
10 \\
11 \\
12 \\
\end{bmatrix}
- 10
=
\begin{bmatrix}
10 \\
11 \\
12 \\
\end{bmatrix}
- 10\cdot \mathbf{1}
=
\begin{bmatrix}
10 \\
11 \\
12 \\
\end{bmatrix}
-
\begin{bmatrix}
10 \\
10 \\
10 \\
\end{bmatrix}
\end{align}
\end{split}

In [38]:
c = 5
c * np.array([2, 5])

array([10, 25])

In [39]:
np.array([[10, 11, 12]]) - 10


array([[0, 1, 2]])

## 선형조합
벡터/행렬에 다음처럼 스칼라값을 곱한 후 더하거나 뺀 것을 벡터/행렬의 **선형조합(linear combination)**이라고 한다. 벡터나 행렬을 선형조합해도 크기는 변하지 않는다.

In [42]:
# 두 벡터의 곱
x = np.array([[1], [2], [3]]) #열벡터
y = np.array([[4], [5], [6]]) #열벡터
print(x.T) # 행벡터

x.T @ y  # 또는 np.dot(x.T, y)  => 행벡터 @내적 열벡터
# 1*4 + 2*5 + 3*6 = 32

[[1 2 3]]


array([[32]])

In [43]:
 # 두 행렬의 곱
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# 행 곱하기 행
x @ y  # 또는 np.dot(x, y)

32

벡터의 내적은 가중합을 계산할 때 쓰일 수 있다. **가중합(weighted sum)**이란 복수의 데이터를 단순히 합하는 것이 아니라 각각의 수에 어떤 가중치 값을 곱한 후 이 곱셈 결과들을 다시 합한 것을 말한다.

\begin{align}
w_1 x_1 + \cdots + w_N x_N = \sum_{i=1}^N w_i x_i 
\end{align}


\begin{split} 
\begin{align}
\begin{aligned}
\sum_{i=1}^N w_i x_i 
&= 
\begin{bmatrix}
w_{1} && w_{2} && \cdots && w_{N}
\end{bmatrix}
\begin{bmatrix}
x_1 \\ x_2 \\ \vdots \\ x_N
\end{bmatrix} 
&= w^Tx  
\\
&=
\begin{bmatrix}
x_{1} && x_{2} && \cdots && x_{N}
\end{bmatrix}
\begin{bmatrix}
w_1 \\ w_2 \\ \vdots \\ w_N
\end{bmatrix}
&= x^Tw  
\end{aligned}
\end{align}
\end{split}

In [45]:
# 평균 계산
a = np.arange(10)
print("a=", a)
N = len(a)
print(np.ones(N))
print(np.ones(N)@a)  # 가중합 계산
np.ones(N) @ a / N

a= [0 1 2 3 4 5 6 7 8 9]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
45.0


4.5

In [47]:
a.mean()

4.5

\begin{split}
\begin{align}
x^T x = 
\begin{bmatrix}
x_{1} & x_{2} & \cdots & x_{N} 
\end{bmatrix}
\begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{N} \\
\end{bmatrix} = \sum_{i=1}^{N} x_i^2
\end{align}
\end{split}

\begin{split}
\begin{align}
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
\tag{2.2.42}
\end{align}
\end{split}
\begin{split}
\begin{align}
B = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}
\tag{2.2.43}
\end{align}
\end{split}
\begin{split}
\begin{align}
C = AB = \begin{bmatrix} 22 & 28 \\ 49 & 64 \end{bmatrix}
\end{align}
\end{split}

In [50]:
A = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3 행렬
B = np.array([[1, 2], [3, 4], [5, 6]]) #3x2 행렬
C = A @ B
C # 2x2 행렬

array([[22, 28],
       [49, 64]])

Q. 순서를 바꾸어 BA를 손으로 계산하고 넘파이의 계산 결과와 맞는지 확인한다. BA가 AB와 같은가?

In [51]:
C = B @ A
C # 3x3 행렬

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

## 교환법칙과 분배법칙
\begin{align}
AB \neq BA  
\end{align}
\begin{align}
A(B + C) = AB + AC  
\end{align}
\begin{align}
(A + B)C = AC + BC  
\end{align}

In [52]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 8], [7, 6]])

### 교환법칙
교환법칙은 벡터의 연산에서 해당되지 않는다.

In [53]:
A @ B

array([[19, 22],
       [43, 50]])

In [54]:
B @ A

array([[23, 34],
       [31, 46]])

### 분배법칙은 다음 두 식이 같다.

In [55]:
A @ (B + C)

array([[42, 42],
       [98, 98]])

In [56]:
A @ B + A @ C

array([[42, 42],
       [98, 98]])

In [57]:
(A + B) @ C

array([[110,  96],
       [174, 152]])

In [58]:
A @ C + B @ C

array([[110,  96],
       [174, 152]])

In [59]:
(A @ B).T

array([[19, 43],
       [22, 50]])

In [60]:
B.T @ A.T #전치를 할 때는 서로 A와 B의 순서가 바뀐다!!!!!!!!

array([[19, 43],
       [22, 50]])

# 행렬의 역행렬

In [63]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])


In [65]:
Ainv = np.linalg.inv(A) #리니어알제브라=>선형대수를 영어로 한것, inv는 역행렬을 나오게 만듬
print(A)
print(Ainv)

[[1 1 0]
 [0 1 1]
 [1 1 1]]
[[ 0. -1.  1.]
 [ 1.  1. -1.]
 [-1.  0.  1.]]


In [66]:
A@Ainv #원래 행렬과 역행렬을 곱하면 항등행렬이 나온다.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])